[toolchain]
anchor_version = "0.29.0"   # CLI
solana_version = "1.16.27"

[features]
resolution = false
skip-lint = false

[workspace]
members = [
    "programs/swap-layer"
]

[programs.localnet]
swap_layer = "AQFz751pSuxMX6PFWx9uruoVSZ3qay2Zi33MJ4NmUF2m"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "ts/tests/keys/pFCBP4bhqdSsrWUVTgqhPsLrfEdChBK17vgFM7TxjxQ.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 ts/tests/[1-9]*.ts"

[test]
startup_wait = 20000

[test.validator]
url = "https://api.devnet.solana.com"

### At 160 ticks/s, 64 ticks per slot implies that leader rotation and voting will happen
### every 400 ms. A fast voting cadence ensures faster finality and convergence
ticks_per_slot = 16

### Wormhole Core Bridge Program
[[test.validator.clone]]
address = "3u8hJUVTA4jH1wYAyUur7FFZVQ8H635K3tSHHF4ssjQ5"

### Circle Message Transmitter Program
[[test.validator.clone]]
address = "CCTPmbSD7gX1bxKPAmg77w8oFzNFpaQiQUWD43TKaecd"

### Circle Token Messenger Minter Program
[[test.validator.clone]]
address = "CCTPiPYPc6AsJuwueEnWgSgucamXDZwBd53dQ11YiKX3"

### Mint -- USDC
[[test.validator.account]]
address = "4zMMC9srt5Ri5X14GAgXhaHii3GnPAEERYPJgZJDncDU"
filename = "../lib/example-liquidity-layer/solana/ts/tests/accounts/usdc_mint.json"

### Payer Token Account -- USDC
[[test.validator.account]]
address = "6s9vuDVXZsJY1Qp29cFxKgbSmpTH2QWnrjZzPHWmFXCz"
filename = "../lib/example-liquidity-layer/solana/ts/tests/accounts/usdc_payer_token.json"

### Circle Token Messenger Minter PDA -- Token Messenger
[[test.validator.account]]
address = "Afgq3BHEfCE7d78D2XE9Bfyu2ieDqvE24xX8KDwreBms"
filename = "../lib/example-liquidity-layer/solana/ts/tests/accounts/token_messenger_minter/token_messenger.json"

### Circle Token Messenger Minter PDA -- Token Minter
[[test.validator.account]]
address = "DBD8hAwLDRQkTsu6EqviaYNGKPnsAMmQonxf7AH8ZcFY"
filename = "../lib/example-liquidity-layer/solana/ts/tests/accounts/token_messenger_minter/token_minter.json"

### Circle Token Messenger Minter PDA -- USDC Custody Token Account
[[test.validator.account]]
address = "AEfKU8wHGtYgsXpymQ6e1cGHJJeKqCj95pw82iyRUKEs"
filename = "../lib/example-liquidity-layer/solana/ts/tests/accounts/token_messenger_minter/usdc_custody_token.json"

### Circle Token Messenger Minter PDA -- USDC Local Token
[[test.validator.account]]
address = "4xt9P42CcMHXAgvemTnzineHp6owfGUcrg1xD9V7mdk1"
filename = "../lib/example-liquidity-layer/solana/ts/tests/accounts/token_messenger_minter/usdc_local_token.json"

### Circle Token Messenger Minter PDA -- USDC Token Pair
[[test.validator.account]]
address = "ADcG1d7znq6wR73BJgEh7dR4vTJcETLLyfXMNZjJVwk4"
filename = "../lib/example-liquidity-layer/solana/ts/tests/accounts/token_messenger_minter/usdc_token_pair.json"

### Circle Token Messenger Minter PDA -- Ethereum Remote Token Messenger
[[test.validator.account]]
address = "Hazwi3jFQtLKc2ughi7HFXPkpDeso7DQaMR9Ks4afh3j"
filename = "../lib/example-liquidity-layer/solana/ts/tests/accounts/token_messenger_minter/ethereum_remote_token_messenger.json"

### Circle Token Messenger Minter PDA -- Arbitrum Remote Token Messenger
[[test.validator.account]]
address = "REzxi9nX3Eqseha5fBiaJhTC6SFJx4qJhP83U4UCrtc"
filename = "../lib/example-liquidity-layer/solana/ts/tests/accounts/token_messenger_minter/arbitrum_remote_token_messenger.json"

### Circle Token Messenger Minter PDA -- Base Remote Token Messenger
[[test.validator.account]]
address = "BWyFzH6LsnmDAaDWbGsriQ9SiiKq1CF6pbH4Ye3kzSBV"
filename = "../lib/example-liquidity-layer/solana/ts/tests/accounts/token_messenger_minter/misconfigured_remote_token_messenger.json"

### Circle Message Transmitter PDA -- Message Transmitter Config
[[test.validator.account]]
address = "BWrwSWjbikT3H7qHAkUEbLmwDQoB4ZDJ4wcSEhSPTZCu"
filename = "../lib/example-liquidity-layer/solana/ts/tests/accounts/message_transmitter/message_transmitter_config.json"

### Wormhole Core Bridge -- Config
[[test.validator.account]]
address = "6bi4JGDoRwUs9TYBuvoA7dUVyikTJDrJsJU1ew6KVLiu"
filename = "../lib/example-liquidity-layer/solana/ts/tests/accounts/core_bridge/config.json"

### Wormhole Core Bridge -- Fee Collector
[[test.validator.account]]
address = "7s3a1ycs16d6SNDumaRtjcoyMaTDZPavzgsmS3uUZYWX"
filename = "../lib/example-liquidity-layer/solana/ts/tests/accounts/core_bridge/fee_collector.json"

### Wormhole Core Bridge -- Guardian Set 0
[[test.validator.account]]
address = "dxZtypiKT5D9LYzdPxjvSZER9MgYfeRVU5qpMTMTRs4"
filename = "../lib/example-liquidity-layer/solana/ts/tests/accounts/core_bridge/guardian_set_0.json"

### Testnet Matching Engine Program
[[test.validator.clone]]
address = "mPydpGUWxzERTNpyvTKdvS7v8kvw5sgwfiP8WQFrXVS"

### Testnet Matching Engine -- Custodian
[[test.validator.account]]
address = "5BsCKkzuZXLygduw6RorCqEB61AdzNkxp5VzQrFGzYWr"
filename = "../lib/example-liquidity-layer/solana/ts/tests/accounts/testnet/matching_engine_custodian.json"

### Testnet Token Router Program
[[test.validator.clone]]
address = "tD8RmtdcV7bzBeuFgyrFc8wvayj988ChccEzRQzo6md"

### Testnet Token Router -- Custodian
[[test.validator.clone]]
address = "CFYdtHYDnQgCAcwetWVjVg5V8Uiy1CpJaoYJxmV19Z7N"

### Testnet Token Router - Sepolia Endpoint
[[test.validator.clone]]
address = "7GKCHT6kxRGmJJYuKXUkBzzxKXbnyEHa79nuQeeHKVxW"

### Testnet Token Router - Mint Recipient
[[test.validator.clone]]
address = "EPEpG3P1Vvak3stx7RnwQD9vWFLpWzpXnbfXc1owrD7o"

### Payer USDC Token Account
[[test.validator.account]]
address = "4tKtuvtQ4TzkkrkESnRpbfSXCEZPkZe3eL5tCFUdpxtf"
filename = "ts/tests/accounts/payer_usdc_token.json"

### Payer USDT Token Account
[[test.validator.account]]
address = "4MXG73DEVVRN9xiJavCkFVFtZdYBrKmD1hjxmTtNoZnA"
filename = "ts/tests/accounts/payer_usdt_token.json"

### NOTE: The accounts below are from mainnet.

### USDC Mint (Mainnet)
[[test.validator.account]]
address = "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v"
filename = "ts/tests/accounts/usdc_mint.json"

### USDT Mint (Mainnet)
[[test.validator.account]]
address = "Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB"
filename = "ts/tests/accounts/usdt_mint.json"

### Wormhole Core Bridge Program (Mainnet)
[[test.genesis]]
address = "worm2ZoG2kUd4vFXhvjh93UUH596ayRfgQ2MgjNMTth"
program = "ts/tests/artifacts/mainnet_core_bridge.so"

### Jupiter V6 Program (Mainnet)
[[test.genesis]]
address = "JUP6LkbZbjS1jKKwapdHNy74zcZ3tLUZoi5QNyVTaV4"
program = "ts/tests/artifacts/mainnet_jupiter_v6.so"

### Whirlpool Program (Mainnet)
[[test.genesis]]
address = "whirLbMiicVdio4qvUfM5KAg6Ct8VwpYzGff3uctyCc"
program = "ts/tests/artifacts/mainnet_whirlpool.so"

### Jupiter V6 -- Custody Token Owner
[[test.validator.account]]
address = "BQ72nSv9f3PRyRKCBnHLVrerrv37CYTHm5h3s9VSGQDV"
filename = "ts/tests/accounts/jupiter/jupiter_custody_owner.json"

### Jupiter V6 -- USDC Custody Token
[[test.validator.account]]
address = "7u7cD7NxcZEuzRCBaYo8uVpotRdqZwez47vvuwzCov43"
filename = "ts/tests/accounts/jupiter/jupiter_usdc_custody_token.json"

### Jupiter V6 -- USDT Custody Token
[[test.validator.account]]
address = "6pXVFSACE5BND2C3ibGRWMG1fNtV7hfynWrfNKtCXhN3"
filename = "ts/tests/accounts/jupiter/jupiter_usdt_custody_token.json"

### Jupiter V6 -- LUT #1
[[test.validator.account]]
address = "GxS6FiQ3mNnAar9HGQ6mxP7t6FcwmHkU7peSeQDUHmpN"
filename = "ts/tests/accounts/jupiter/jupiter_lut1.json"

### Whirlpool -- USDC-USDT Pool
[[test.validator.account]]
address = "4fuUiYxTQ6QCrdSq9ouBYcTM7bqSwYTSyLueGZLTy4T4"
filename = "ts/tests/accounts/whirlpool/whirlpool_usdc_usdt_pool.json"

### Whirlpool -- USDC-USDT Pool -- USDC Vault
[[test.validator.account]]
address = "4oY1eVHJrt7ywuFoQnAZwto4qcQip1QhYMAhD11PU4QL"
filename = "ts/tests/accounts/whirlpool/whirlpool_usdc_vault.json"

### Whirlpool -- USDC-USDT Pool -- USDT Vault
[[test.validator.account]]
address = "4dSG9tKHZR4CAictyEnH9XuGZyKapodWXq5xyg7uFwE9"
filename = "ts/tests/accounts/whirlpool/whirlpool_usdt_vault.json"

### Whirlpool -- USDC-USDT Pool Tick Array 0
[[test.validator.account]]
address = "8kZSTVuV7C4GD9ZVR4wDtRSXv1SvsSQPfqUbthueRNGV"
filename = "ts/tests/accounts/whirlpool/whirlpool_usdc_usdt_tick_array_0.json"

### Whirlpool -- USDC-USDT Pool Tick Array 1A
[[test.validator.account]]
address = "2B48L1ACPvVb67UKeSMkUGdzrnhvNMm6pFt2nspGKxs4"
filename = "ts/tests/accounts/whirlpool/whirlpool_usdc_usdt_tick_array_1a.json"

### Whirlpool -- USDC-USDT Pool Tick Array 2A
[[test.validator.account]]
address = "BMGfBaW69aUm6hRdmsfAcNEmAW59C2rWJ9EX7gWnrVN9"
filename = "ts/tests/accounts/whirlpool/whirlpool_usdc_usdt_tick_array_2a.json"

### Whirlpool -- USDC-USDT Pool Tick Array 1B
[[test.validator.account]]
address = "FqFkv2xNNCUyx1RYV61pGZ9AMzGfgcD8uXC9zCF5JKnR"
filename = "ts/tests/accounts/whirlpool/whirlpool_usdc_usdt_tick_array_1b.json"

### Whirlpool -- USDC-USDT Pool Tick Array 2B
[[test.validator.account]]
address = "A7sdy3NoAZp49cQNpreMGARAb9QJjYrrSyDALhThgk3D"
filename = "ts/tests/accounts/whirlpool/whirlpool_usdc_usdt_tick_array_2b.json"