[toolchain]
anchor_version = "0.29.0"   # CLI
solana_version = "1.16.27"

[features]
seeds = false
skip-lint = false

[programs.localnet]
swap_layer = "AQFz751pSuxMX6PFWx9uruoVSZ3qay2Zi33MJ4NmUF2m"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "ts/tests/keys/pFCBP4bhqdSsrWUVTgqhPsLrfEdChBK17vgFM7TxjxQ.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 ts/tests/[0-9]*.ts"

[test]
startup_wait = 20000

[test.validator]
url = "https://api.devnet.solana.com"

### At 160 ticks/s, 64 ticks per slot implies that leader rotation and voting will happen
### every 400 ms. A fast voting cadence ensures faster finality and convergence
ticks_per_slot = 16

### Wormhole Core Bridge Program
[[test.validator.clone]]
address = "3u8hJUVTA4jH1wYAyUur7FFZVQ8H635K3tSHHF4ssjQ5"

### Circle Message Transmitter Program
[[test.validator.clone]]
address = "CCTPmbSD7gX1bxKPAmg77w8oFzNFpaQiQUWD43TKaecd"

### Circle Token Messenger Minter Program
[[test.validator.clone]]
address = "CCTPiPYPc6AsJuwueEnWgSgucamXDZwBd53dQ11YiKX3"

### Mint -- USDC
[[test.validator.account]]
address = "4zMMC9srt5Ri5X14GAgXhaHii3GnPAEERYPJgZJDncDU"
filename = "lib/example-liquidity-layer/solana/ts/tests/accounts/usdc_mint.json"

### Payer Token Account -- USDC
[[test.validator.account]]
address = "6s9vuDVXZsJY1Qp29cFxKgbSmpTH2QWnrjZzPHWmFXCz"
filename = "lib/example-liquidity-layer/solana/ts/tests/accounts/usdc_payer_token.json"

### Circle Token Messenger Minter PDA -- Token Messenger
[[test.validator.account]]
address = "Afgq3BHEfCE7d78D2XE9Bfyu2ieDqvE24xX8KDwreBms"
filename = "lib/example-liquidity-layer/solana/ts/tests/accounts/token_messenger_minter/token_messenger.json"

### Circle Token Messenger Minter PDA -- Token Minter
[[test.validator.account]]
address = "DBD8hAwLDRQkTsu6EqviaYNGKPnsAMmQonxf7AH8ZcFY"
filename = "lib/example-liquidity-layer/solana/ts/tests/accounts/token_messenger_minter/token_minter.json"

### Circle Token Messenger Minter PDA -- USDC Custody Token Account
[[test.validator.account]]
address = "AEfKU8wHGtYgsXpymQ6e1cGHJJeKqCj95pw82iyRUKEs"
filename = "lib/example-liquidity-layer/solana/ts/tests/accounts/token_messenger_minter/usdc_custody_token.json"

### Circle Token Messenger Minter PDA -- USDC Local Token
[[test.validator.account]]
address = "4xt9P42CcMHXAgvemTnzineHp6owfGUcrg1xD9V7mdk1"
filename = "lib/example-liquidity-layer/solana/ts/tests/accounts/token_messenger_minter/usdc_local_token.json"

### Circle Token Messenger Minter PDA -- USDC Token Pair
[[test.validator.account]]
address = "ADcG1d7znq6wR73BJgEh7dR4vTJcETLLyfXMNZjJVwk4"
filename = "lib/example-liquidity-layer/solana/ts/tests/accounts/token_messenger_minter/usdc_token_pair.json"

### Circle Token Messenger Minter PDA -- Ethereum Remote Token Messenger
[[test.validator.account]]
address = "Hazwi3jFQtLKc2ughi7HFXPkpDeso7DQaMR9Ks4afh3j"
filename = "lib/example-liquidity-layer/solana/ts/tests/accounts/token_messenger_minter/ethereum_remote_token_messenger.json"

### Circle Token Messenger Minter PDA -- Arbitrum Remote Token Messenger
[[test.validator.account]]
address = "REzxi9nX3Eqseha5fBiaJhTC6SFJx4qJhP83U4UCrtc"
filename = "lib/example-liquidity-layer/solana/ts/tests/accounts/token_messenger_minter/arbitrum_remote_token_messenger.json"

### Circle Token Messenger Minter PDA -- Base Remote Token Messenger
[[test.validator.account]]
address = "BWyFzH6LsnmDAaDWbGsriQ9SiiKq1CF6pbH4Ye3kzSBV"
filename = "lib/example-liquidity-layer/solana/ts/tests/accounts/token_messenger_minter/misconfigured_remote_token_messenger.json"

### Circle Message Transmitter PDA -- Message Transmitter Config
[[test.validator.account]]
address = "BWrwSWjbikT3H7qHAkUEbLmwDQoB4ZDJ4wcSEhSPTZCu"
filename = "lib/example-liquidity-layer/solana/ts/tests/accounts/message_transmitter/message_transmitter_config.json"

### Wormhole Core Bridge -- Config
[[test.validator.account]]
address = "6bi4JGDoRwUs9TYBuvoA7dUVyikTJDrJsJU1ew6KVLiu"
filename = "lib/example-liquidity-layer/solana/ts/tests/accounts/core_bridge/config.json"

### Wormhole Core Bridge -- Fee Collector
[[test.validator.account]]
address = "7s3a1ycs16d6SNDumaRtjcoyMaTDZPavzgsmS3uUZYWX"
filename = "lib/example-liquidity-layer/solana/ts/tests/accounts/core_bridge/fee_collector.json"

### Wormhole Core Bridge -- Guardian Set 0
[[test.validator.account]]
address = "dxZtypiKT5D9LYzdPxjvSZER9MgYfeRVU5qpMTMTRs4"
filename = "lib/example-liquidity-layer/solana/ts/tests/accounts/core_bridge/guardian_set_0.json"

### Testnet Matching Engine Program
[[test.validator.clone]]
address = "mPydpGUWxzERTNpyvTKdvS7v8kvw5sgwfiP8WQFrXVS"

### Testnet Matching Engine -- Custodian
[[test.validator.account]]
address = "5BsCKkzuZXLygduw6RorCqEB61AdzNkxp5VzQrFGzYWr"
filename = "lib/example-liquidity-layer/solana/ts/tests/accounts/testnet/matching_engine_custodian.json"

### Testnet Token Router Program
[[test.validator.clone]]
address = "tD8RmtdcV7bzBeuFgyrFc8wvayj988ChccEzRQzo6md"

### Testnet Token Router -- Custodian
[[test.validator.clone]]
address = "CFYdtHYDnQgCAcwetWVjVg5V8Uiy1CpJaoYJxmV19Z7N"