[toolchain]
anchor_version = "0.29.0"   # CLI
solana_version = "1.16.27"

[features]
seeds = false
skip-lint = false

[programs.localnet]
swap_layer = "AQFz751pSuxMX6PFWx9uruoVSZ3qay2Zi33MJ4NmUF2m"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "ts/tests/keys/pFCBP4bhqdSsrWUVTgqhPsLrfEdChBK17vgFM7TxjxQ.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 ts/tests/[0-9]*.ts"
